# Full struct in cmd/prowgen/prowgen.go#Config

config:
  branches:
    "release-1.9":
      openShiftVersions:
        - 4.12
        - 4.10

repositories:
  - org: openshift-knative
    repo: net-kourier
    imagePrefix: net-kourier
    slackChannel: "#knative-serving-ci"
