# Full struct in cmd/prowgen/prowgen.go#Config

config:
  branches:
    "release-v1.4":
      openShiftVersions:
        - 4.11
        - 4.6
    "release-v1.5":
      openShiftVersions:
        - 4.11
        - 4.8
    "release-v1.6":
      openShiftVersions:
        - 4.11
        - 4.8
    "release-v1.7":
      openShiftVersions:
        - 4.11
        - 4.8
    "release-v1.8":
      openShiftVersions:
        - 4.11
        - 4.8
    "release-next":
      openShiftVersions:
        - 4.11
        - 4.8
  resources:
    '*':
      requests:
        cpu: 500m
        memory: 4Gi

repositories:
  - org: openshift-knative
    repo: serving
    imagePrefix: knative-serving
    slackChannel: "#knative-serving-ci"
    e2e:
      matches:
        - ".*e2e$"
        - ".*reconciler.*"
        - ".*conformance.*"
